wc.rbを追加
lsesmpmido/ruby-practices pull request #8
Opened 2024-09-09 02:40 UTC by lsesmpmido

以下の仕様を満たすように設計
- `l`、`w`、`c`の各オプションに対応
- ファイルを1つだけ指定する場合、複数のファイルを指定する場合の両方に対応
- lsコマンドをパイプで入力したものをwcコマンドで出力できるように対応

2024-09-14 16:25 UTC, u1tnk requested changes
各部分コメントしましたが、あとデータ構造なんですが、 file_infoに入っている計算結果と pathsが別に保存されていて、「同じ順番が対応している」という危うい条件で対応しているのは良くないですね。
同じ配列に入っているとか hashを使うとか一つにまとめましょう。

あと、totalはデータ構造にあっても良いですが、必要なときだけ計算してすぐ出力するでも良いですね。

2024-09-14 16:25 UTC, u1tnk commented on 05.wc/wc.rb
> +def contais_path(paths, file_info)
この contais_pathはどういう意味でしょうか？ contaisがどの英単語か分かりませんでした。

2024-09-14 16:25 UTC, u1tnk commented on 05.wc/wc.rb
> +def add_info(content, file_info)
引数に渡した変数を変更するのは良くないです。
必要な情報は帰り値で戻してもらって扱うようにしましょう。

2024-09-14 16:25 UTC, u1tnk commented on 05.wc/wc.rb
> +  file_info = { lines: [], words: [], bytes: [] }
変数名の命名ですが、 infoは抽象度が高すぎて何が入っているか分からないことが多いです。

https://u1tnk.github.io/blog/2022/12/04/naming_variable/

で命名についてまとめたので参考になれば 🙏

2024-09-14 16:25 UTC, u1tnk commented on 05.wc/wc.rb
> +  paths = load_option(options).empty? ? [''] : load_option(options)
load_optionは一行二回実行するのは無駄が多いので一回で済むようにしましょう。

2024-09-14 16:25 UTC, u1tnk commented on 05.wc/wc.rb
> +  total_info = { lines: [], words: [], bytes: [] }
totalは計算してすぐ出力すれば良いので別に変数を用意する必要は無いですね。
複雑で用意した方が良いときもありますが、データの場所は増やさない方が分かりやすいですね。

2024-09-17 16:19 UTC, u1tnk requested changes

2024-09-17 16:19 UTC, u1tnk commented on 05.wc/wc.rb
> +def load_option(options)
load_optionという名前で pathが返ってくるのはおかしいですね。メソッド名を再考お願いします。
また、optionsも引数に変更を入れているので、やめましょう。

2024-09-17 16:19 UTC, u1tnk commented on 05.wc/wc.rb
> +  file_metadata = { lines: [], words: [], bytes: [], paths: [] }
指摘漏れてましたが、この構成だと、どこかの配列に挿入されただけでズレるので安全では無いです。

`[{line_count: 1, word_count: 2, byte_count: 3, path: '/path/to/file.txt'}]`

みたいに配列にひとまとめのhashを入れるようにした方がまとまりがはっきりしますね。

2024-09-17 16:19 UTC, u1tnk commented on 05.wc/wc.rb
> +  file_metadata = { lines: [], words: [], bytes: [], paths: [] }
変数名はブログを参考にしてもらったんだと思いますが、この名前は単数のときならアリと思うんですが、複数だと dataに複数形が無いのもあってちょっと分かりづらいですね。
あんまり例が良くなかったかも 🙏

2024-09-17 16:19 UTC, u1tnk commented on 05.wc/wc.rb
> +  if paths[0].nil?
ここで標準入力か判断していますが、ちょっと分かりづらいと思います。
load_optionか直後にして欲しいと思います。

2024-09-17 16:19 UTC, u1tnk commented on 05.wc/wc.rb
> +def add_metadata(content, path = '')
add_xxxを使うとしたらクラスを使うようになったときに `users.add_user` みたいにするとusersにuserを追加するというように使います。

この場合は calc_metadataとかget_metadataが良いかなと思います。

2024-09-17 16:19 UTC, u1tnk commented on 05.wc/wc.rb
> +      metadata = add_metadata(File.read(path), path)
ここですが、 `File.read(path), path` は両方 pathがあれば良いので 引数をpathだけにした方が良いかと思います。

2024-09-17 16:19 UTC, u1tnk commented on 05.wc/wc.rb
> +def show_metadata(metadata, index, width, options = {})
optionsを渡さないケースは無さそなので  ` = {}` のデフォルト値は不要と思います。

2024-09-18 16:51 UTC, u1tnk requested changes

2024-09-18 16:51 UTC, u1tnk commented on 05.wc/wc.rb
> +  filtered_metadata_list = metadata_list.map { |metadata| metadata.reject { |_, value| value.is_a?(String) } }
細かいですが、 Integerの最大長を取るという意図なら分かりますが、 String以外となると意図が分かりづらくなります。
結果は一緒ですが意図が伝わりやすい方を選びましょう。

2024-09-18 16:51 UTC, u1tnk commented on 05.wc/wc.rb
> +  width = max_value.to_s.length
ここは widthだと 「色々計算したけど何の幅？」ってなるので名前を改善しましょう。

2024-09-18 16:51 UTC, u1tnk commented on 05.wc/wc.rb
> +  metadata_list = paths.empty? ? [get_metadata] : contains_paths(paths)
まあmetadataが複数形無いので付けたという経緯は分かってるし、意図が伝わりにくいわけでは無いので今回はこの名前でOKですが、 ruby界隈で `_list`、 `_array` は大体指摘されるので今後はやめましょう。

2024-09-18 16:51 UTC, u1tnk commented on 05.wc/wc.rb
> +def contains_paths(paths)
すみません前回指摘漏れたみたいですが、contains_pathしたら metadataのlistが返ってくるというのは理解しづらいので名前の改善お願いします。

2024-09-18 16:51 UTC, u1tnk commented on 05.wc/wc.rb
> +  content = path.empty? ? $stdin.read : File.read(path)
前よりは良いと思うんですが、 pathが空だったら 標準入力というのはちょっと分かりづらいので、この部分を呼び出し前にして文字列を渡すようにすると良いと思います。

2024-09-18 19:39 UTC, lsesmpmido commented on 05.wc/wc.rb
> +  metadata_list = paths.empty? ? [get_metadata] : contains_paths(paths)
>  ruby界隈で _list、 _array は大体指摘されるので今後はやめましょう。

申し訳ございません。
dataが単数名詞だったら複数名詞にすることで配列名にすることもできたと思うのですが、dataという名詞がそもそもdatumの複数形ですし、かといって私の語彙が乏しく～data以外の適切な配列名が思い浮かばなかったのでこのような安直な対応を取らせていただきました。次回からは気を付けたいと思います。

2024-09-19 17:02 UTC, u1tnk approved these changes

2024-09-20 00:47 UTC, merged